// Code generated by github.com/deweppro/go-static. DO NOT EDIT.
package demo

import "github.com/deweppro/go-static"

func init() {
	//ui static archive
	ui = func(s string) static.Reader {
		c := static.New()
		if err := c.FromBase64TarGZ(s); err != nil {
			panic(err.Error())
		}
		return c
	}("H4sIAAAAAAAA/+zSwUrEMBAG4F47TzHk1Aqm0z1swbNHDyJ7l9hOY9AkJZnoQXx3WXcR3KssstDvMjBzmGT4u4l9fBTOom2szoOIaBiG70pEp5U225/Zod/3235TIZ3pPb+ULCZV9Oddp5+7EIsZX4xl3McAwPklJsEGajV7UVCrfTJcsAqgVtbJc3nSY/TdxO+8LCl2Nl5nMeJGBS1A19l4YzlwMsJ4GKDG4gDeTMLijj39wGbiBDCXMOKOs9yyj43g1XGf3rX4AfXsRd8nF+Q1NMXpO5elaVv4hP8+22q1Wl28rwAAAP//20if1wAIAAA=")
}

/* FILES:
/demo_test.go
*/
