// Code generated by go.osspkg.com/static. DO NOT EDIT.
package demo

import "go.osspkg.com/static"

func init() {
	//ui static archive
	ui = func(s string) static.Reader {
		c := static.New()
		if err := c.FromBase64TarGZ(s); err != nil {
			panic(err.Error())
		}
		return c
	}("H4sIAAAAAAAA/+yUz4vTQBTHe+38FV96SgqdTNNtCyKidvcgriLuepbZ5GUyNJkp86NQxf9dOq4eelFYqhTzubzwHsl7Yd5nipp6y5UdnREhhFiv1ykKIU6jWC6ufj2n/Fwsl2IEcc6hfhJ9kG4kntzr9OcuhGLKMAU2dndwWrUBWZWjFOV8VopygXd620rd4a05yC8t7fG8l24b/aqcv1S91B2vbP+C41XXIb3v4ciT21PN04c/eYJtEFrt4W10FaGyNUF7KLsnZ6jGwwESr++uZ4vZppPREzpdkfGE0MqASho8EBobTQ1tEFrC7ZvNzfu7GzS6o2OjgrGdrLZSEY4LzZjud9YFZGw8afowYWw8UZZb73dbdZy58EEGXU1YzlhRKPtMkSEnA+FHARxRM7aXDlE/5vhHkjU5xppoKrhoshxf2bjpA//gtAmdyaLmt9qHLM/ZN/avz/ZPSP5/DuTD+S6B3/l/Va5O/J+vxHrw/2/wH/h/XG5tVFI9mXtPPlxTb7OA6WOR3yeVk9MXYu7AwMDA0/geAAD//4cOBIcADAAA")
}

/* FILES:
/demo.go
/demo_test.go
*/
