// Code generated by github.com/deweppro/go-static. DO NOT EDIT.
package demo

import "github.com/deweppro/go-static"

func init() {
	//ui static archive
	ui = func(s string) static.Reader {
		c := static.New()
		if err := c.FromBase64TarGZ(s); err != nil {
			panic(err.Error())
		}
		return c
	}("H4sIAAAAAAAA/+yUT0v0MBCH97rzKUJP7QtvOnVXC549ehDZu8R2GoMmKelED+J3l42rh4J4kCqLeS4TZg75w+9J3ZP1UvvVgiAitm2bKiLOK55sNh/r1G/wdLtdCVzyUO/EiVVY4bf3ml/uSBhVd680iX0MAIwdfWBRwroYLBcA60Ibvou3svO27umJxjH4Wvv/Eys2XQEVQF1rf67JUVBM4m0gpIgG4FEFEc2hJ69J9RQAhug6EaIrK/EM68GyvArG8YMro5GXZuKyquAFfvtp/gTJ/xumiZf7BL7yv2m2M/+bM2yy/z/Bp/7vI2GcToYnYXc08QVZX7L4dxjKXTI4qZyFzWQymaPiNQAA///3bgL2AAwAAA==")
}

/* FILES:
/demo.go
/demo_test.go
*/
