// Code generated by github.com/osspkg/go-static. DO NOT EDIT.
package demo

import "github.com/osspkg/go-static"

func init() {
	//ui static archive
	ui = func(s string) static.Reader {
		c := static.New()
		if err := c.FromBase64TarGZ(s); err != nil {
			panic(err.Error())
		}
		return c
	}("H4sIAAAAAAAA/+yUP0s0MRCHr935FGGr3Rfe7OQ8XbC2tBC5XuJeNoYzyZJMbMTvLhdPiwWxkFUO8zQTZor84fek2ynrufarBUFE7Ps+V0ScV1yfiY917gs836xXDJc81Dspkgwr/PZe88udCJMc9lIrdogBgLGTD8QaqOrRUg1Q1drQQ7rng7edj3Ha6077/5EkmaGGFqDrtL/UyqkgSbG3AeMsGYAnGVgyxx6/VXKnAsCY3MBCck3LnqEaLfGbYBw9uiYZfm0iNW0LL/DbD/NHyP7fkYq03Cfwlf9CbGb+iwsUxf+f4FP/D5EwTmfHs7JbFelKWd8Q+3cc8m12OMtclC0UCoWT4jUAAP//KtzKpgAMAAA=")
}

/* FILES:
/demo.go
/demo_test.go
*/
