package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/deweppro/go-static"
)

var template = `// Code generated by github.com/deweppro/go-static. DO NOT EDIT.
package %s

import "github.com/deweppro/go-static"

func init() {
	//%s static archive
	%s = func(s string) static.Reader {
		c := static.New()
		if err := c.FromBase64TarGZ(s); err != nil {
			panic(err.Error())
		}
		return c
	}("%s")
}

/* FILES:
%s
*/
`

func main() {
	flag.Parse()
	args := flag.Args()
	if len(args) < 2 {
		panic("bad args count")
	}

	path, err := os.Getwd()
	if err != nil {
		panic(err.Error())
	}

	spath := strings.Split(path, "/")
	pack := spath[len(spath)-1]

	cache := static.New()
	err = cache.FromDir(path + "/" + args[0])
	if err != nil {
		panic(err.Error())
	}

	b64, err := cache.ToBase64TarGZ()
	if err != nil {
		panic(err.Error())
	}

	data := fmt.Sprintf(template, pack, args[1], args[1], b64, strings.Join(cache.List(), "\n"))
	err = os.WriteFile(pack+"_static.go", []byte(data), os.ModePerm)
	if err != nil {
		panic(err.Error())
	}
}
