package main

import (
	"flag"
	"fmt"
	"io/ioutil"
	"os"
	"strings"

	"github.com/deweppro/go-static"
)

var template = `// Code generated by github.com/deweppro/go-static. DO NOT EDIT.
package %s

func init() {
	//%s static archive
	%s = "%s"
}
`

func main() {
	flag.Parse()
	args := flag.Args()
	if len(args) < 2 {
		panic("bad args count")
	}

	path, err := os.Getwd()
	if err != nil {
		panic(err)
	}

	spath := strings.Split(path, "/")
	pack := spath[len(spath)-1]

	cache := static.New()
	cache.FromDir(args[0])

	b64, err := cache.ToBase64TarGZ()
	if err != nil {
		panic(err)
	}

	data := fmt.Sprintf(template, pack, args[1], args[1], b64)
	err = ioutil.WriteFile(pack+"_static.go", []byte(data), os.ModePerm)
	if err != nil {
		panic(err)
	}
}
