// Code generated by github.com/deweppro/go-static. DO NOT EDIT.
package example

func init() {
	//UI static archive
	UI = "H4sIAAAAAAAA/+zSz0ozMRAA8F4zTzHfnpLDl6S1tFDpxYNSEPFgL95izG6Dm2SZzVpB+u7SbfFQvFkowv4uEyaTyR+ipFTuw4SmdioYH2WVRuemtdbz+byPWuvTqK9ms+9xnx9PppPxCPXZT/KDrs2GRvrXe51e7o9ojH0zlcPjHwDwoUmUkQMrypALAFZUPm+6F2lTUK9u65qGkqrS/zab7G0BAkCpKi0qFx2Z7PAwgVJJiesVwLshXK9wiUUBUHbRInWRC/wEZo3dOFwsj2vkg9tyAcyX6Ij2+b5A3lIKN6Z1s+mTobtnvl6J677i3xKjr/edWGOit9wRCWA7AFaGLB/Jx1xHfuhy79vMhYAdXPrVB4PB4PK+AgAA//8WutnVAAgAAA=="
}
